/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.wa_hrp_002;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-06-25 13:24:23
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PsnOutStaffVO extends SuperVO {
	private UFDateTime ts;
	private String vdef9;
	private String vdef17;
	private String vdef20;
	private String vdef1;
	private String vdef8;
	private String vdef10;
	private String idno;
	private String psnname;
	private String bankno;
	private String psncode;
	private String vdef15;
	private String vdef14;
	private String vdef7;
	private String vdef13;
	private String vdef16;
	private String vdef2;
	private String vdef5;
	private String vdef11;
	private String psntype;
	private String vdef19;
	private String pk_outstaff;
	private String vdef3;
	private UFDate dmakedate;
	private String vdef12;
	private String vdef6;
	private Integer dr;
	private String account;
	private String pk_dept;
	private String vdef18;
	private String vdef4;
	private String remark;

	public static final String VDEF9 = "vdef9";
	public static final String VDEF17 = "vdef17";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String IDNO = "idno";
	public static final String PSNNAME = "psnname";
	public static final String BANKNO = "bankno";
	public static final String PSNCODE = "psncode";
	public static final String VDEF15 = "vdef15";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF13 = "vdef13";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF11 = "vdef11";
	public static final String PSNTYPE = "psntype";
	public static final String VDEF19 = "vdef19";
	public static final String PK_OUTSTAFF = "pk_outstaff";
	public static final String VDEF3 = "vdef3";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String ACCOUNT = "account";
	public static final String PK_DEPT = "pk_dept";
	public static final String VDEF18 = "vdef18";
	public static final String VDEF4 = "vdef4";
	public static final String REMARK = "remark";
			
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性idno的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getIdno () {
		return idno;
	}   
	/**
	 * 属性idno的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newIdno String
	 */
	public void setIdno (String newIdno ) {
	 	this.idno = newIdno;
	} 	  
	/**
	 * 属性psnname的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getPsnname () {
		return psnname;
	}   
	/**
	 * 属性psnname的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newPsnname String
	 */
	public void setPsnname (String newPsnname ) {
	 	this.psnname = newPsnname;
	} 	  
	/**
	 * 属性bankno的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getBankno () {
		return bankno;
	}   
	/**
	 * 属性bankno的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newBankno String
	 */
	public void setBankno (String newBankno ) {
	 	this.bankno = newBankno;
	} 	  
	/**
	 * 属性psncode的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getPsncode () {
		return psncode;
	}   
	/**
	 * 属性psncode的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newPsncode String
	 */
	public void setPsncode (String newPsncode ) {
	 	this.psncode = newPsncode;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性psntype的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getPsntype () {
		return psntype;
	}   
	/**
	 * 属性psntype的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newPsntype String
	 */
	public void setPsntype (String newPsntype ) {
	 	this.psntype = newPsntype;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性pk_outstaff的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getPk_outstaff () {
		return pk_outstaff;
	}   
	/**
	 * 属性pk_outstaff的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newPk_outstaff String
	 */
	public void setPk_outstaff (String newPk_outstaff ) {
	 	this.pk_outstaff = newPk_outstaff;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return UFDate
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate (UFDate newDmakedate ) {
	 	this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性account的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getAccount () {
		return account;
	}   
	/**
	 * 属性account的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newAccount String
	 */
	public void setAccount (String newAccount ) {
	 	this.account = newAccount;
	} 	  
	/**
	 * 属性pk_dept的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getPk_dept () {
		return pk_dept;
	}   
	/**
	 * 属性pk_dept的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newPk_dept String
	 */
	public void setPk_dept (String newPk_dept ) {
	 	this.pk_dept = newPk_dept;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性remark的Getter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @return String
	 */
	public String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.
	 * 创建日期:2019-06-25 13:24:23
	 * @param newRemark String
	 */
	public void setRemark (String newRemark ) {
	 	this.remark = newRemark;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-06-25 13:24:23
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-06-25 13:24:23
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_outstaff";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-06-25 13:24:23
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "WA_PSN_OUTSTAFF";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-06-25 13:24:23
	  */
     public PsnOutStaffVO() {
		super();	
	}    
} 
