/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.tam.tongren020;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-04-28 10:22:44
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class WorkDayBVO extends SuperVO {
	private UFDateTime ts;
	private String vdef9;
	private String vdef17;
	private String pk_bb7;
	private String vdef20;
	private String vdef1;
	private String vdef8;
	private String vdef10;
	private String pk_psndoc;
	private String vbbname3;
	private String pk_bb3;
	private String pk_deptdoc;
	private String vdef15;
	private UFDouble workdays;
	private String vbbname2;
	private String vdef14;
	private String vdef7;
	private String vdef13;
	private String vbbname1;
	private String vbbname4;
	private String pk_bb1;
	private String pk_workday_b;
	private String vbbname7;
	private String vdef2;
	private String vdef16;
	private String pk_bb2;
	private String vdef5;
	private String pk_bb6;
	private String vdef11;
	private String vdef19;
	private String vbbname6;
	private String vdef3;
	private String vdef12;
	private String vdef6;
	private String pk_workday_h;
	private String pk_dept;
	private String pk_bb4;
	private Integer dr;
	private String vdef4;
	private String vdef18;
	private String vbbname5;
	private String pk_bb5;

	public static final String VDEF9 = "vdef9";
	public static final String VDEF17 = "vdef17";
	public static final String PK_BB7 = "pk_bb7";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String VBBNAME3 = "vbbname3";
	public static final String PK_BB3 = "pk_bb3";
	public static final String PK_DEPTDOC = "pk_deptdoc";
	public static final String VDEF15 = "vdef15";
	public static final String WORKDAYS = "workdays";
	public static final String VBBNAME2 = "vbbname2";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF13 = "vdef13";
	public static final String VBBNAME1 = "vbbname1";
	public static final String VBBNAME4 = "vbbname4";
	public static final String PK_BB1 = "pk_bb1";
	public static final String PK_WORKDAY_B = "pk_workday_b";
	public static final String VBBNAME7 = "vbbname7";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF16 = "vdef16";
	public static final String PK_BB2 = "pk_bb2";
	public static final String VDEF5 = "vdef5";
	public static final String PK_BB6 = "pk_bb6";
	public static final String VDEF11 = "vdef11";
	public static final String VDEF19 = "vdef19";
	public static final String VBBNAME6 = "vbbname6";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String PK_WORKDAY_H = "pk_workday_h";
	public static final String PK_DEPT = "pk_dept";
	public static final String PK_BB4 = "pk_bb4";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF18 = "vdef18";
	public static final String VBBNAME5 = "vbbname5";
	public static final String PK_BB5 = "pk_bb5";
			
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性pk_bb7的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb7 () {
		return pk_bb7;
	}   
	/**
	 * 属性pk_bb7的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb7 String
	 */
	public void setPk_bb7 (String newPk_bb7 ) {
	 	this.pk_bb7 = newPk_bb7;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性pk_psndoc的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_psndoc () {
		return pk_psndoc;
	}   
	/**
	 * 属性pk_psndoc的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_psndoc String
	 */
	public void setPk_psndoc (String newPk_psndoc ) {
	 	this.pk_psndoc = newPk_psndoc;
	} 	  
	/**
	 * 属性vbbname3的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname3 () {
		return vbbname3;
	}   
	/**
	 * 属性vbbname3的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname3 String
	 */
	public void setVbbname3 (String newVbbname3 ) {
	 	this.vbbname3 = newVbbname3;
	} 	  
	/**
	 * 属性pk_bb3的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb3 () {
		return pk_bb3;
	}   
	/**
	 * 属性pk_bb3的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb3 String
	 */
	public void setPk_bb3 (String newPk_bb3 ) {
	 	this.pk_bb3 = newPk_bb3;
	} 	  
	/**
	 * 属性pk_deptdoc的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_deptdoc () {
		return pk_deptdoc;
	}   
	/**
	 * 属性pk_deptdoc的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_deptdoc String
	 */
	public void setPk_deptdoc (String newPk_deptdoc ) {
	 	this.pk_deptdoc = newPk_deptdoc;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性workdays的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDouble
	 */
	public UFDouble getWorkdays () {
		return workdays;
	}   
	/**
	 * 属性workdays的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newWorkdays UFDouble
	 */
	public void setWorkdays (UFDouble newWorkdays ) {
	 	this.workdays = newWorkdays;
	} 	  
	/**
	 * 属性vbbname2的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname2 () {
		return vbbname2;
	}   
	/**
	 * 属性vbbname2的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname2 String
	 */
	public void setVbbname2 (String newVbbname2 ) {
	 	this.vbbname2 = newVbbname2;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性vbbname1的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname1 () {
		return vbbname1;
	}   
	/**
	 * 属性vbbname1的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname1 String
	 */
	public void setVbbname1 (String newVbbname1 ) {
	 	this.vbbname1 = newVbbname1;
	} 	  
	/**
	 * 属性vbbname4的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname4 () {
		return vbbname4;
	}   
	/**
	 * 属性vbbname4的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname4 String
	 */
	public void setVbbname4 (String newVbbname4 ) {
	 	this.vbbname4 = newVbbname4;
	} 	  
	/**
	 * 属性pk_bb1的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb1 () {
		return pk_bb1;
	}   
	/**
	 * 属性pk_bb1的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb1 String
	 */
	public void setPk_bb1 (String newPk_bb1 ) {
	 	this.pk_bb1 = newPk_bb1;
	} 	  
	/**
	 * 属性pk_workday_b的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_workday_b () {
		return pk_workday_b;
	}   
	/**
	 * 属性pk_workday_b的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_workday_b String
	 */
	public void setPk_workday_b (String newPk_workday_b ) {
	 	this.pk_workday_b = newPk_workday_b;
	} 	  
	/**
	 * 属性vbbname7的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname7 () {
		return vbbname7;
	}   
	/**
	 * 属性vbbname7的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname7 String
	 */
	public void setVbbname7 (String newVbbname7 ) {
	 	this.vbbname7 = newVbbname7;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性pk_bb2的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb2 () {
		return pk_bb2;
	}   
	/**
	 * 属性pk_bb2的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb2 String
	 */
	public void setPk_bb2 (String newPk_bb2 ) {
	 	this.pk_bb2 = newPk_bb2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性pk_bb6的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb6 () {
		return pk_bb6;
	}   
	/**
	 * 属性pk_bb6的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb6 String
	 */
	public void setPk_bb6 (String newPk_bb6 ) {
	 	this.pk_bb6 = newPk_bb6;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性vbbname6的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname6 () {
		return vbbname6;
	}   
	/**
	 * 属性vbbname6的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname6 String
	 */
	public void setVbbname6 (String newVbbname6 ) {
	 	this.vbbname6 = newVbbname6;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性pk_workday_h的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_workday_h () {
		return pk_workday_h;
	}   
	/**
	 * 属性pk_workday_h的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_workday_h String
	 */
	public void setPk_workday_h (String newPk_workday_h ) {
	 	this.pk_workday_h = newPk_workday_h;
	} 	  
	/**
	 * 属性pk_dept的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_dept () {
		return pk_dept;
	}   
	/**
	 * 属性pk_dept的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_dept String
	 */
	public void setPk_dept (String newPk_dept ) {
	 	this.pk_dept = newPk_dept;
	} 	  
	/**
	 * 属性pk_bb4的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb4 () {
		return pk_bb4;
	}   
	/**
	 * 属性pk_bb4的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb4 String
	 */
	public void setPk_bb4 (String newPk_bb4 ) {
	 	this.pk_bb4 = newPk_bb4;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vbbname5的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVbbname5 () {
		return vbbname5;
	}   
	/**
	 * 属性vbbname5的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbbname5 String
	 */
	public void setVbbname5 (String newVbbname5 ) {
	 	this.vbbname5 = newVbbname5;
	} 	  
	/**
	 * 属性pk_bb5的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_bb5 () {
		return pk_bb5;
	}   
	/**
	 * 属性pk_bb5的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_bb5 String
	 */
	public void setPk_bb5 (String newPk_bb5 ) {
	 	this.pk_bb5 = newPk_bb5;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-04-28 10:22:44
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "PK_WORKDAY_H";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-04-28 10:22:44
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_workday_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-04-28 10:22:44
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "TRTAM_WORKDAY_B";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-04-28 10:22:44
	  */
     public WorkDayBVO() {
		super();	
	}    
} 
