/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.tam.tongren020;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-04-28 10:22:44
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class WorkDayHVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String vdef9;
	private String vdef17;
	private String vdef20;
	private String vdef1;
	private String vdef8;
	private String vdef10;
	private String vapproveid;
	private UFDate createoperate;
	private String vdef15;
	private String vdef14;
	private String vdef7;
	private UFDate dapprovedate;
	private String vdef13;
	private String vdef16;
	private String vdef2;
	private UFDate enddate;
	private String vdef5;
	private String vdef11;
	private String vdef19;
	private Integer vbillstatus;
	private String voperatorid;
	private UFDate dmakedate;
	private String vdef3;
	private String vdef12;
	private String vdef6;
	private String pk_workday_h;
	private Integer dr;
	private String vdef18;
	private String vdef4;
	private UFDate begindate;
	private String remark;
	private String pk_wa_period;

	public static final String PK_WA_PERIOD = "pk_wa_period";
	public static final String PK_CORP = "pk_corp";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF17 = "vdef17";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String VAPPROVEID = "vapproveid";
	public static final String CREATEOPERATE = "createoperate";
	public static final String VDEF15 = "vdef15";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF7 = "vdef7";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VDEF13 = "vdef13";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF2 = "vdef2";
	public static final String ENDDATE = "enddate";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF11 = "vdef11";
	public static final String VDEF19 = "vdef19";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VOPERATORID = "voperatorid";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String PK_WORKDAY_H = "pk_workday_h";
	public static final String VDEF18 = "vdef18";
	public static final String VDEF4 = "vdef4";
	public static final String BEGINDATE = "begindate";
	public static final String REMARK = "remark";
			
	
	
	public String getPk_wa_period() {
		return pk_wa_period;
	}
	public void setPk_wa_period(String pk_wa_period) {
		this.pk_wa_period = pk_wa_period;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性createoperate的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDateTime
	 */
	public UFDate getCreateoperate () {
		return createoperate;
	}   
	/**
	 * 属性createoperate的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newCreateoperate UFDateTime
	 */
	public void setCreateoperate (UFDate newCreateoperate ) {
	 	this.createoperate = newCreateoperate;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性enddate的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDate
	 */
	public UFDate getEnddate () {
		return enddate;
	}   
	/**
	 * 属性enddate的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newEnddate UFDate
	 */
	public void setEnddate (UFDate newEnddate ) {
	 	this.enddate = newEnddate;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDouble
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDate
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate (UFDate newDmakedate ) {
	 	this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性pk_workday_h的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getPk_workday_h () {
		return pk_workday_h;
	}   
	/**
	 * 属性pk_workday_h的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newPk_workday_h String
	 */
	public void setPk_workday_h (String newPk_workday_h ) {
	 	this.pk_workday_h = newPk_workday_h;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性begindate的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return UFDate
	 */
	public UFDate getBegindate () {
		return begindate;
	}   
	/**
	 * 属性begindate的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newBegindate UFDate
	 */
	public void setBegindate (UFDate newBegindate ) {
	 	this.begindate = newBegindate;
	} 	  
	/**
	 * 属性remark的Getter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @return String
	 */
	public String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.
	 * 创建日期:2019-04-28 10:22:44
	 * @param newRemark String
	 */
	public void setRemark (String newRemark ) {
	 	this.remark = newRemark;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-04-28 10:22:44
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-04-28 10:22:44
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_workday_h";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-04-28 10:22:44
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "TRTAM_WORKDAY_H";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-04-28 10:22:44
	  */
     public WorkDayHVO() {
		super();	
	}    
} 
