/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.tam.tongren.power;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-09-11 09:45:45
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class UserClassTypeBVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private UFDate vdef9;
	private String vdef1;
	private String vdef8;
	private UFBoolean vdef10;
	private String pk_bclbid;
	private String vdef2;
	private UFBoolean vdef5;
	private String pk_hrp_classtype_b;
	private String pk_user;
	private String vdef3;
	private UFDouble vdef6;
	private Integer dr;
	private UFDate vdef4;
	private String pk_hrp_classtype;
	private UFDouble vdef7;

	public static final String PK_CORP = "pk_corp";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String PK_BB = "pk_bb";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String PK_HRP_CLASSTYPE_B = "pk_hrp_classtype_b";
	public static final String PK_USER = "pk_user";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF4 = "vdef4";
	public static final String PK_HRP_CLASSTYPE = "pk_hrp_classtype";
	public static final String VDEF7 = "vdef7";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFDate
	 */
	public UFDate getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef9 UFDate
	 */
	public void setVdef9 (UFDate newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFBoolean
	 */
	public UFBoolean getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef10 UFBoolean
	 */
	public void setVdef10 (UFBoolean newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
		  
	public String getPk_bclbid() {
		return pk_bclbid;
	}
	public void setPk_bclbid(String pk_bclbid) {
		this.pk_bclbid = pk_bclbid;
	}
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFBoolean
	 */
	public UFBoolean getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef5 UFBoolean
	 */
	public void setVdef5 (UFBoolean newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性pk_hrp_classtype_b的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getPk_hrp_classtype_b () {
		return pk_hrp_classtype_b;
	}   
	/**
	 * 属性pk_hrp_classtype_b的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newPk_hrp_classtype_b String
	 */
	public void setPk_hrp_classtype_b (String newPk_hrp_classtype_b ) {
	 	this.pk_hrp_classtype_b = newPk_hrp_classtype_b;
	} 	  
	/**
	 * 属性pk_user的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getPk_user () {
		return pk_user;
	}   
	/**
	 * 属性pk_user的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newPk_user String
	 */
	public void setPk_user (String newPk_user ) {
	 	this.pk_user = newPk_user;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFDouble
	 */
	public UFDouble getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef6 UFDouble
	 */
	public void setVdef6 (UFDouble newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFDate
	 */
	public UFDate getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef4 UFDate
	 */
	public void setVdef4 (UFDate newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性pk_hrp_classtype的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return String
	 */
	public String getPk_hrp_classtype () {
		return pk_hrp_classtype;
	}   
	/**
	 * 属性pk_hrp_classtype的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newPk_hrp_classtype String
	 */
	public void setPk_hrp_classtype (String newPk_hrp_classtype ) {
	 	this.pk_hrp_classtype = newPk_hrp_classtype;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @return UFDouble
	 */
	public UFDouble getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2019-09-11 09:45:45
	 * @param newVdef7 UFDouble
	 */
	public void setVdef7 (UFDouble newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-09-11 09:45:45
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-09-11 09:45:45
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_hrp_classtype_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-09-11 09:45:45
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "TRTAM_CLASSTYPE_KQ_B";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-09-11 09:45:45
	  */
     public UserClassTypeBVO() {
		super();	
	}    
} 
