/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.wa_hrp_012;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-08-23 09:59:21
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class RedDashedBVO extends SuperVO {
	private UFDateTime ts;
	private UFDouble rednnmy;
	private String vdef9;
	private String vdef17;
	private String vdef20;
	private UFDouble vdef1;
	private String vdef8;
	private String pk_reddashed_b;
	private String vdef10;
	private UFDouble occnnmy;
	private String pk_deptdoc;
	private String vdef15;
	private String rowno;
	private UFDouble outnmny;
	private String vdef14;
	private String vdef7;
	private String vdef13;
	private UFDouble nmny;
	private UFDouble diffnnmy;
	private UFDouble vdef2;
	private String vdef16;
	private UFDouble vdef5;
	private String vdef11;
	private UFDouble effectnnmy;
	private String vdef19;
	private UFDouble innmny;
	private UFDouble vdef3;
	private String vdef12;
	private String vdef6;
	private String vbillno;
	private Integer dr;
	private UFDouble vdef4;
	private String pk_reddashed_h;
	private String vdef18;
	private String remark;

	public static final String REDNNMY = "rednnmy";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF17 = "vdef17";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String PK_REDDASHED_B = "pk_reddashed_b";
	public static final String VDEF10 = "vdef10";
	public static final String OCCNNMY = "occnnmy";
	public static final String PK_DEPTDOC = "pk_deptdoc";
	public static final String VDEF15 = "vdef15";
	public static final String ROWNO = "rowno";
	public static final String OUTNMNY = "outnmny";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF13 = "vdef13";
	public static final String NMNY = "nmny";
	public static final String DIFFNNMY = "diffnnmy";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF11 = "vdef11";
	public static final String EFFECTNNMY = "effectnnmy";
	public static final String VDEF19 = "vdef19";
	public static final String INNMNY = "innmny";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String VBILLNO = "vbillno";
	public static final String VDEF4 = "vdef4";
	public static final String PK_REDDASHED_H = "pk_reddashed_h";
	public static final String VDEF18 = "vdef18";
	public static final String REMARK = "remark";
			
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性rednnmy的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getRednnmy () {
		return rednnmy;
	}   
	/**
	 * 属性rednnmy的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newRednnmy UFDouble
	 */
	public void setRednnmy (UFDouble newRednnmy ) {
	 	this.rednnmy = newRednnmy;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef1 UFDouble
	 */
	public void setVdef1 (UFDouble newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性pk_reddashed_b的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getPk_reddashed_b () {
		return pk_reddashed_b;
	}   
	/**
	 * 属性pk_reddashed_b的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newPk_reddashed_b String
	 */
	public void setPk_reddashed_b (String newPk_reddashed_b ) {
	 	this.pk_reddashed_b = newPk_reddashed_b;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性occnnmy的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getOccnnmy () {
		return occnnmy;
	}   
	/**
	 * 属性occnnmy的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newOccnnmy UFDouble
	 */
	public void setOccnnmy (UFDouble newOccnnmy ) {
	 	this.occnnmy = newOccnnmy;
	} 	  
	/**
	 * 属性pk_deptdoc的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getPk_deptdoc () {
		return pk_deptdoc;
	}   
	/**
	 * 属性pk_deptdoc的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newPk_deptdoc String
	 */
	public void setPk_deptdoc (String newPk_deptdoc ) {
	 	this.pk_deptdoc = newPk_deptdoc;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性rowno的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getRowno () {
		return rowno;
	}   
	/**
	 * 属性rowno的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newRowno String
	 */
	public void setRowno (String newRowno ) {
	 	this.rowno = newRowno;
	} 	  
	/**
	 * 属性outnmny的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getOutnmny () {
		return outnmny;
	}   
	/**
	 * 属性outnmny的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newOutnmny UFDouble
	 */
	public void setOutnmny (UFDouble newOutnmny ) {
	 	this.outnmny = newOutnmny;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性nmny的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getNmny () {
		return nmny;
	}   
	/**
	 * 属性nmny的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newNmny UFDouble
	 */
	public void setNmny (UFDouble newNmny ) {
	 	this.nmny = newNmny;
	} 	  
	/**
	 * 属性diffnnmy的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getDiffnnmy () {
		return diffnnmy;
	}   
	/**
	 * 属性diffnnmy的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newDiffnnmy UFDouble
	 */
	public void setDiffnnmy (UFDouble newDiffnnmy ) {
	 	this.diffnnmy = newDiffnnmy;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef2 UFDouble
	 */
	public void setVdef2 (UFDouble newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef5 UFDouble
	 */
	public void setVdef5 (UFDouble newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性effectnnmy的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getEffectnnmy () {
		return effectnnmy;
	}   
	/**
	 * 属性effectnnmy的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newEffectnnmy UFDouble
	 */
	public void setEffectnnmy (UFDouble newEffectnnmy ) {
	 	this.effectnnmy = newEffectnnmy;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性innmny的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getInnmny () {
		return innmny;
	}   
	/**
	 * 属性innmny的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newInnmny UFDouble
	 */
	public void setInnmny (UFDouble newInnmny ) {
	 	this.innmny = newInnmny;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef3 UFDouble
	 */
	public void setVdef3 (UFDouble newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return UFDouble
	 */
	public UFDouble getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef4 UFDouble
	 */
	public void setVdef4 (UFDouble newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性pk_reddashed_h的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getPk_reddashed_h () {
		return pk_reddashed_h;
	}   
	/**
	 * 属性pk_reddashed_h的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newPk_reddashed_h String
	 */
	public void setPk_reddashed_h (String newPk_reddashed_h ) {
	 	this.pk_reddashed_h = newPk_reddashed_h;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性remark的Getter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @return String
	 */
	public String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.
	 * 创建日期:2019-08-23 09:59:21
	 * @param newRemark String
	 */
	public void setRemark (String newRemark ) {
	 	this.remark = newRemark;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-08-23 09:59:21
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "PK_REDDASHED_H";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-08-23 09:59:21
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_reddashed_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-08-23 09:59:21
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "WA_REDDASHED_B";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-08-23 09:59:21
	  */
     public RedDashedBVO() {
		super();	
	}    
} 
